<template>
  <div>
    <h2>User Profile</h2>
    <button @click="login">Log in</button>
    <pre v-if="isAuthenticated">
      <code>{{ user }}</code>
    </pre>
    <button @click="doSomethingWithToken">Get Access Token</button>
  </div>
</template>

<script>
import { useAuth0 } from '@auth0/auth0-vue';

export default {
  setup() {
    const { loginWithRedirect, user, isAuthenticated, getAccessTokenSilently } = useAuth0();

    const login = () => {
      loginWithRedirect();
    };

    const doSomethingWithToken = async () => {
      try {
        const token = await getAccessTokenSilently();
        console.log(token);

        // Check if the user exists
        const response = await fetch('https://localhost:7286/api/User', {
          headers: {
            Authorization: 'Bearer ' + token
          }
        });

        const data = await response.json();

        if (data.error && data.error.includes('User not found')) {
          // Create the user
          const createUserResponse = await fetch('https://localhost:7286/api/User', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              Authorization: 'Bearer ' + token
            },
            body: JSON.stringify({
              id: generateHexCode(),  // Autogenerated hex code
              email: user.email,  // Using the email from Auth0
              activityIds: []  // Empty array
            })
          });

          const createUserResult = await createUserResponse.json();

          if (createUserResult.error) {
            console.error(createUserResult.error);
          } else {
            console.log('User created:', createUserResult);
          }
        } else {
          console.log('User already exists:', data);
        }

      } catch (error) {
        console.error(error);
      }
    };

    // Function to generate a random hexadecimal code
    const generateHexCode = () => {
      return [...Array(24)].map(() => Math.floor(Math.random() * 16).toString(16)).join('');
    };

  return {
    login,
    user,
    isAuthenticated,
    doSomethingWithToken,
  };
},
  };
</script>
