name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
    sonarqube:
        runs-on: ubuntu-latest
      
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
      
            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                java-version: '11'
      
            - name: Run SonarQube scanner
              run: |
                C:/sonar-scanner/bin/sonar-scanner.bat -X \
                  -D"sonar.projectKey=S3Frontend" \
                  -D"sonar.sources=." \
                  -D"sonar.host.url=http://localhost:9000" \
                  -D"sonar.token=${{ secrets.SONAR_TOKEN }}"


        