name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: SonarQube Scan
        run: sonar-scanner \
             -Dsonar.projectKey=S3Frontend \

             -Dsonar.host.url=https://localhost:9000 \
             -Dsonar.login=your_token

        